foreach(INFINI_RT_REQUIRED_VARIABLE
        IN ITEMS
            INFINI_RT_INSTALL_PREFIX
            INFINI_RT_REQUIRED_VERSION
            INFINI_RT_CONSUMER_SOURCE_DIR
            INFINI_RT_CONSUMER_SOURCE
            INFINI_RT_CONSUMER_BINARY
            INFINI_RT_CTEST_COMMAND)
    if(NOT DEFINED ${INFINI_RT_REQUIRED_VARIABLE}
       OR "${${INFINI_RT_REQUIRED_VARIABLE}}" STREQUAL "")
        message(FATAL_ERROR
                "${INFINI_RT_REQUIRED_VARIABLE} is required for the install consumer test.")
    endif()
endforeach()

set(INFINI_RT_CONFIGURE_ARGS
    -S "${INFINI_RT_CONSUMER_SOURCE_DIR}"
    -B "${INFINI_RT_CONSUMER_BINARY}"
    "-DCMAKE_PREFIX_PATH=${INFINI_RT_INSTALL_PREFIX}"
    "-DINFINI_RT_REQUIRED_VERSION=${INFINI_RT_REQUIRED_VERSION}"
    "-DINFINI_RT_CONSUMER_SOURCE=${INFINI_RT_CONSUMER_SOURCE}"
    "-DINFINI_RT_CONSUMER_BACKEND=${INFINI_RT_CONSUMER_BACKEND}")

if(INFINI_RT_CMAKE_GENERATOR)
    list(APPEND INFINI_RT_CONFIGURE_ARGS
         -G "${INFINI_RT_CMAKE_GENERATOR}")
endif()
if(INFINI_RT_CMAKE_GENERATOR_PLATFORM)
    list(APPEND INFINI_RT_CONFIGURE_ARGS
         -A "${INFINI_RT_CMAKE_GENERATOR_PLATFORM}")
endif()
if(INFINI_RT_CMAKE_GENERATOR_TOOLSET)
    list(APPEND INFINI_RT_CONFIGURE_ARGS
         -T "${INFINI_RT_CMAKE_GENERATOR_TOOLSET}")
endif()
if(INFINI_RT_CMAKE_BUILD_TYPE)
    list(APPEND INFINI_RT_CONFIGURE_ARGS
         "-DCMAKE_BUILD_TYPE=${INFINI_RT_CMAKE_BUILD_TYPE}")
endif()
if(INFINI_RT_CXX_COMPILER)
    list(APPEND INFINI_RT_CONFIGURE_ARGS
         "-DCMAKE_CXX_COMPILER=${INFINI_RT_CXX_COMPILER}")
endif()
if(INFINI_RT_CMAKE_TOOLCHAIN_FILE)
    list(APPEND INFINI_RT_CONFIGURE_ARGS
         "-DCMAKE_TOOLCHAIN_FILE=${INFINI_RT_CMAKE_TOOLCHAIN_FILE}")
endif()
if(INFINI_RT_CUDATOOLKIT_ROOT)
    list(APPEND INFINI_RT_CONFIGURE_ARGS
         "-DCUDAToolkit_ROOT=${INFINI_RT_CUDATOOLKIT_ROOT}")
endif()
if(INFINI_RT_BACKEND_ROOT_VARIABLE AND INFINI_RT_BACKEND_ROOT)
    list(APPEND INFINI_RT_CONFIGURE_ARGS
         "-D${INFINI_RT_BACKEND_ROOT_VARIABLE}=${INFINI_RT_BACKEND_ROOT}")
endif()

execute_process(
    COMMAND "${CMAKE_COMMAND}" ${INFINI_RT_CONFIGURE_ARGS}
    RESULT_VARIABLE INFINI_RT_CONFIGURE_RESULT
    OUTPUT_VARIABLE INFINI_RT_CONFIGURE_OUTPUT
    ERROR_VARIABLE INFINI_RT_CONFIGURE_ERROR)

if(NOT INFINI_RT_CONFIGURE_RESULT EQUAL 0)
    message(FATAL_ERROR
            "Configuring the install consumer failed.\n"
            "${INFINI_RT_CONFIGURE_OUTPUT}\n${INFINI_RT_CONFIGURE_ERROR}")
endif()

set(INFINI_RT_BUILD_ARGS --build "${INFINI_RT_CONSUMER_BINARY}")
if(INFINI_RT_BUILD_CONFIG)
    list(APPEND INFINI_RT_BUILD_ARGS --config "${INFINI_RT_BUILD_CONFIG}")
endif()

execute_process(
    COMMAND "${CMAKE_COMMAND}" ${INFINI_RT_BUILD_ARGS}
    RESULT_VARIABLE INFINI_RT_BUILD_RESULT
    OUTPUT_VARIABLE INFINI_RT_BUILD_OUTPUT
    ERROR_VARIABLE INFINI_RT_BUILD_ERROR)

if(NOT INFINI_RT_BUILD_RESULT EQUAL 0)
    message(FATAL_ERROR
            "Building the install consumer failed.\n"
            "${INFINI_RT_BUILD_OUTPUT}\n${INFINI_RT_BUILD_ERROR}")
endif()

set(INFINI_RT_CTEST_ARGS --output-on-failure)
if(INFINI_RT_BUILD_CONFIG)
    list(APPEND INFINI_RT_CTEST_ARGS -C "${INFINI_RT_BUILD_CONFIG}")
endif()

execute_process(
    COMMAND "${INFINI_RT_CTEST_COMMAND}" ${INFINI_RT_CTEST_ARGS}
    WORKING_DIRECTORY "${INFINI_RT_CONSUMER_BINARY}"
    RESULT_VARIABLE INFINI_RT_RUN_RESULT
    OUTPUT_VARIABLE INFINI_RT_RUN_OUTPUT
    ERROR_VARIABLE INFINI_RT_RUN_ERROR)

if(NOT INFINI_RT_RUN_RESULT EQUAL 0)
    message(FATAL_ERROR
            "Running the install consumer failed.\n"
            "${INFINI_RT_RUN_OUTPUT}\n${INFINI_RT_RUN_ERROR}")
endif()
