set(INFINI_RT_INCLUDE_DIR "${INFINI_RT_INSTALL_PREFIX}/include")
set(INFINI_RT_LIBRARY_DIR "${INFINI_RT_INSTALL_PREFIX}/lib")

if(NOT EXISTS "${INFINI_RT_LIBRARY_DIR}/libinfinirt.so")
    set(INFINI_RT_LIBRARY_DIR "${INFINI_RT_INSTALL_PREFIX}/lib64")
endif()

if(NOT EXISTS "${INFINI_RT_INCLUDE_DIR}/infini/rt.h")
    message(FATAL_ERROR "The installed public header was not found.")
endif()

if(NOT EXISTS "${INFINI_RT_LIBRARY_DIR}/libinfinirt.so")
    message(FATAL_ERROR "The installed InfiniRT library was not found.")
endif()

set(INFINI_RT_EXTRA_LINK_ARGS "")
set(INFINI_RT_EXTRA_COMPILE_ARGS "")
set(INFINI_RT_LD_LIBRARY_PATH "${INFINI_RT_LIBRARY_DIR}")

if(INFINI_RT_EXTRA_INCLUDE_PATHS)
    string(REPLACE ":" ";" INFINI_RT_EXTRA_INCLUDE_DIRS
           "${INFINI_RT_EXTRA_INCLUDE_PATHS}")
    foreach(INFINI_RT_EXTRA_INCLUDE_DIR ${INFINI_RT_EXTRA_INCLUDE_DIRS})
        if(EXISTS "${INFINI_RT_EXTRA_INCLUDE_DIR}")
            list(APPEND INFINI_RT_EXTRA_COMPILE_ARGS
                 "-I${INFINI_RT_EXTRA_INCLUDE_DIR}")
        endif()
    endforeach()
endif()

if(INFINI_RT_CONSUMER_BACKEND AND NOT INFINI_RT_CONSUMER_BACKEND STREQUAL "NONE")
    list(APPEND INFINI_RT_EXTRA_COMPILE_ARGS
         "-DINFINI_RT_CONSUMER_BACKEND_${INFINI_RT_CONSUMER_BACKEND}=1")
endif()

if(INFINI_RT_EXTRA_LIBRARY_PATHS)
    string(REPLACE ":" ";" INFINI_RT_EXTRA_LIBRARY_DIRS
           "${INFINI_RT_EXTRA_LIBRARY_PATHS}")
    foreach(INFINI_RT_EXTRA_LIBRARY_DIR ${INFINI_RT_EXTRA_LIBRARY_DIRS})
        if(EXISTS "${INFINI_RT_EXTRA_LIBRARY_DIR}")
            list(APPEND INFINI_RT_EXTRA_LINK_ARGS
                 "-Wl,-rpath-link,${INFINI_RT_EXTRA_LIBRARY_DIR}")
            set(INFINI_RT_LD_LIBRARY_PATH
                "${INFINI_RT_LD_LIBRARY_PATH}:${INFINI_RT_EXTRA_LIBRARY_DIR}")
        endif()
    endforeach()
endif()

execute_process(
    COMMAND "${INFINI_RT_CXX_COMPILER}"
            -std=c++17
            -Werror
            "-I${INFINI_RT_INCLUDE_DIR}"
            ${INFINI_RT_EXTRA_COMPILE_ARGS}
            "${INFINI_RT_CONSUMER_SOURCE}"
            "-L${INFINI_RT_LIBRARY_DIR}"
            -linfinirt
            "-Wl,-rpath,${INFINI_RT_LIBRARY_DIR}"
            ${INFINI_RT_EXTRA_LINK_ARGS}
            -o "${INFINI_RT_CONSUMER_BINARY}"
    RESULT_VARIABLE INFINI_RT_COMPILE_RESULT
    OUTPUT_VARIABLE INFINI_RT_COMPILE_OUTPUT
    ERROR_VARIABLE INFINI_RT_COMPILE_ERROR)

if(NOT INFINI_RT_COMPILE_RESULT EQUAL 0)
    message(FATAL_ERROR
            "Compiling the install consumer failed.\n"
            "${INFINI_RT_COMPILE_OUTPUT}\n${INFINI_RT_COMPILE_ERROR}")
endif()

execute_process(
    COMMAND "${CMAKE_COMMAND}" -E env
            "LD_LIBRARY_PATH=${INFINI_RT_LD_LIBRARY_PATH}:$ENV{LD_LIBRARY_PATH}"
            "${INFINI_RT_CONSUMER_BINARY}"
    RESULT_VARIABLE INFINI_RT_RUN_RESULT
    OUTPUT_VARIABLE INFINI_RT_RUN_OUTPUT
    ERROR_VARIABLE INFINI_RT_RUN_ERROR)

if(NOT INFINI_RT_RUN_RESULT EQUAL 0)
    message(FATAL_ERROR
            "Running the install consumer failed.\n"
            "${INFINI_RT_RUN_OUTPUT}\n${INFINI_RT_RUN_ERROR}")
endif()
